### ISSUE TITLE
Using this without composer

### ISSUE THREAD

**Issue by bgold0** [pwhelan/datachore#3]
Thanks so much for making this publicly available. It looks awesome. Having a little trouble installing and using this without composer on my GAE. Anyway you could explain what to include without composer?

**Comment by pwhelan** [comment]
The only necessary include is here: https://github.com/illuminate/support. I use it basically for the collection type, which is here: https://github.com/illuminate/support/blob/master/Collection.php.

You will need to get autoloading working for both libraries as well. Accomplishing this by hand is way beyond the scope this project.

**Comment by pwhelan** [comment]
In any case, I use composer with my GAE projects. Just simply call composer to fill in the vendor directory before deploying and it will work fine.

**Comment by iog3** [comment]
You should use composer and just do as @pwhelan says, or use something like CodeShip which can deploy to App Engine with the dependencies so it doesn't go into your git repo and your team always has the same code.

**Comment by pwhelan** [comment]
I added some more explicit instructions regarding GAE, hope that helps. Closing this for now.
